#define DBG_MAP_MEMORY_MSGBOX 0
#define DBG_LINKED_LIST_MSGBOX 0
#define DBG_REALTIME_MODE_MSGBOX 0
#define DBG_REALTIME_TIMER_MSGBOX 0
#define DBG_EXTREMUM_MSGBOX 0
#define DBG_TOTALGRIDPOINTS_MSGBOX 0
#define DBG_OPENHEIGHTSFILE_MSGBOX 0
#define DBG_DFCS_COORDINATES_MSGBOX 0
#define DBG_MAP_BOUNDS_ERROR_MSGBOX 0
#define DBG_PATHFOUND_MSGBOX 0
#define DBG_MODIFICATION_DETECTED_MSGBOX 0
#define DBG_SCENE_TOTAL_WAYPOINTS_MSGBOX 0
#define DBG_RENDER_TURN_RADIUS_CIRCLES 0
#define DBG_DISCONTINUITY_IN_FL_PAT_DETECTED_MSGBOX 0
#define DBG_INVALID_INITIAL_UAV_HEADING 0
#define DBG_INVALID_FLIGHT_TRAJECTORY_MSGBOX 0

